### PR TITLE
Update 12. Format the text in messages..md

### PR DESCRIPTION
**Pull request by SangeetaMishr**
removed the typo error. added more description

### CODE REVIEW

**Comment by SangeetaMishr** [comment]
@PriyeshSikariwal  Can you please merge this PR.

**Review by PriyeshSikariwal — COMMENTED** [review]
Approved.

**Review by PriyeshSikariwal — APPROVED** [review]
Approved.

**Comment by PriyeshSikariwal** [comment]
Approved.

**Comment by PriyeshSikariwal** [comment]
Approved

**Pull request merged**
